import AppKit
import ApplicationServices
import CryptoKit
import SwiftUI

// Clipboard history. Lives separately from the widget: it has to collect entries
// while the panel is closed too, otherwise history would only contain what was
// copied while the panel happened to be open.
//
// On privacy. The first and main barrier is not saving anything marked secret:
// password managers put org.nspasteboard.ConcealedType on the pasteboard (the
// nspasteboard.org convention), and such entries never touch disk at all. The
// second barrier is an app list: if a password manager is frontmost when a copy
// happens, we skip it. That list exists because not everyone sets the marking,
// and it only costs three lines.
@MainActor @Observable
final class ClipboardStore {
    static let shared = ClipboardStore()

    struct Item: Codable, Identifiable, Equatable, Sendable {
        var id: UUID
        /// The entry's text. An image has none — just a file
        var text: String?
        /// Image file name in the images folder — a snapshot of the content or a file preview
        var image: String?
        /// Path to the file, if a file was copied from Finder. We put back the
        /// original, not a copy: the file could be gigabytes, no reason to drag
        /// it into history
        var file: String?
        /// The app that was frontmost at copy time. The system never tells anyone
        /// who owns the pasteboard, so this is a guess — but usually a right one
        var source: String?
        /// Its bundle id — used to fetch the real app icon
        var sourceID: String?
        var date: Date
        var pinned = false
        /// Content hash of a stored image — repeat copies of the same picture
        /// dedupe by it (text and files dedupe by their own content). Absent
        /// on entries from before the field existed; those simply never match
        var imageHash: String?

        var isImage: Bool { image != nil && file == nil }
        var isFile: Bool { file != nil }

        /// Entry kind — drives the card's label and color
        enum Kind: String, Sendable {
            case text, link, file, image

            var title: String {
                switch self {
                case .text: String(localized: "Text")
                case .link: String(localized: "Link")
                case .file: String(localized: "File")
                case .image: String(localized: "Image")
                }
            }
        }

        var kind: Kind {
            if file != nil { return .file }
            if image != nil { return .image }
            let trimmed = (text ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
            if trimmed.hasPrefix("http://") || trimmed.hasPrefix("https://"),
               !trimmed.contains(" ") {
                return .link
            }
            return .text
        }

        /// Card footer text: character count for text, size for images.
        /// One flat format for every count (no singular/plural split) — a
        /// format string can't carry Russian's three plural forms anyway, so
        /// the localized text is written to read fine at any count
        var measure: String {
            switch kind {
            case .image: String(localized: "image")
            case .file: (file as NSString?)?.pathExtension.uppercased() ?? String(localized: "file")
            default: String(localized: "\((text ?? "").count) characters")
            }
        }

        var kindIcon: String {
            if file != nil { return "doc" }
            if image != nil { return "photo" }
            return "text.alignleft"
        }
    }

    /// One-line preview: line breaks and extra whitespace would only get in the way in a list
    nonisolated static func preview(_ item: Item) -> String {
        if let file = item.file { return (file as NSString).lastPathComponent }
        guard let text = item.text else { return String(localized: "Image") }
        return text
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(of: "\n", with: " ")
    }

    private(set) var items: [Item] = []

    /// Secret entries are never saved at all — the nspasteboard.org convention
    private static let concealed: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// Not everyone sets the marking, so there's also a source app list.
    /// Starting set, editable later in settings
    static let defaultExcludedApps: Set<String> = [
        "com.apple.Passwords",
        "com.apple.keychainaccess",
        "com.1password.1password",
        "com.agilebits.onepassword",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
    ]

    /// macOS has no clipboard-change notification — only a counter. This is the
    /// one place in the project where polling is unavoidable; a single integer,
    /// twice a second
    private static let interval: Duration = .milliseconds(500)

    @ObservationIgnored private var lastChange = NSPasteboard.general.changeCount
    @ObservationIgnored private var task: Task<Void, Never>?
    @ObservationIgnored private var loaded = false
    /// Bumped on every history change — used to invalidate the sort order cache
    @ObservationIgnored private var version = 0

    private init() {}

    // MARK: - lifecycle

    func start() {
        loadIfNeeded()
        guard task == nil else { return }
        lastChange = NSPasteboard.general.changeCount
        task = Task { [weak self] in
            while !Task.isCancelled {
                try? await Task.sleep(for: Self.interval)
                guard let self, !Task.isCancelled else { return }
                capture()
            }
        }
    }

    func stop() {
        task?.cancel()
        task = nil
    }

    /// Setting got toggled — start or stop collecting
    func syncWithSettings() {
        if AppSettings.shared.clipboardEnabled { start() } else { stop() }
    }

    // MARK: - capture

    private func capture() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChange else { return }
        lastChange = pasteboard.changeCount
        dropExpiredIfDue()
        guard AppSettings.shared.clipboardEnabled else { return }

        // Secret content is skipped — checked before reading anything else
        let types = (pasteboard.types ?? []).map(\.rawValue)
        guard !types.contains(where: { Self.concealed.contains($0) }) else { return }

        let front = NSWorkspace.shared.frontmostApplication
        if let id = front?.bundleIdentifier, AppSettings.shared.clipboardExcludedApps.contains(id) {
            return
        }
        // Copying our own history entries back doesn't grow the history
        if front?.bundleIdentifier == Bundle.main.bundleIdentifier, ignoreOwnCopy { return }

        let source = front?.localizedName
        let sourceID = front?.bundleIdentifier

        // Files from Finder arrive as links, not content. Store the path and a
        // small thumbnail — nobody needs a full copy of the file sitting in
        // history. The entry lands immediately and the thumbnail catches up off
        // the main actor: generating it synchronously froze the main thread —
        // a file on a dead network share hung the capsule and the hotkey with it
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL],
           !urls.filter(\.isFileURL).isEmpty {
            // Every file of a multi-selection, not just the first: two of five
            // copied files used to vanish from history without a trace.
            // Reversed so the first selected file ends up as the top entry
            for url in urls.filter(\.isFileURL).reversed() {
                let id = UUID()
                add(Item(id: id, file: url.path, source: source, sourceID: sourceID, date: Date()))
                Task { [weak self] in
                    guard let thumb = await Self.makeThumbnail(of: url) else { return }
                    guard let self, let index = items.firstIndex(where: { $0.id == id }) else {
                        // The entry was deduped away or already evicted — don't orphan the file
                        try? FileManager.default.removeItem(
                            at: Self.imagesDirectory.appending(path: thumb))
                        return
                    }
                    items[index].image = thumb
                    save()
                }
            }
            return
        }
        // Image content: a screenshot, a copy from Preview or a browser. Checked
        // BEFORE text: an image often has a text representation too, and it used
        // to be that text that landed in history while the image itself was lost
        if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff),
           let png = Self.compressed(data) {
            // Deduped by content hash BEFORE writing: files and text collapse
            // repeats, but every re-copied screenshot used to become a new
            // entry and a new PNG on disk
            let hash = Self.hash(png)
            if let index = items.firstIndex(where: { $0.imageHash == hash }) {
                var existing = items.remove(at: index)
                existing.date = Date()
                items.insert(existing, at: 0)
                trim()
                save()
                return
            }
            if let name = Self.store(png: png) {
                add(Item(
                    id: UUID(), image: name, source: source, sourceID: sourceID,
                    date: Date(), imageHash: hash))
                return
            }
        }
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            // Images get scaled down; text can only be skipped whole — a
            // truncated entry would paste back corrupted. A ten-megabyte log
            // used to be rewritten to disk on every following copy
            guard string.utf8.count <= Self.maxTextBytes else {
                sillLog("[clipboard] text of \(string.utf8.count) bytes skipped — over the limit")
                return
            }
            add(Item(id: UUID(), text: string, source: source, sourceID: sourceID, date: Date()))
        }
    }

    /// Above this size text isn't recorded at all: history.json is rewritten
    /// whole on every change, and one giant entry taxes every later copy
    private static let maxTextBytes = 1024 * 1024

    /// Above this size we no longer store an image as-is: a 6K screenshot weighs
    /// close to 50 MB, and a dozen of those eat the disk. Large ones get scaled
    /// down and saved as JPEG
    private static let maxImageBytes = 4 * 1024 * 1024
    private static let maxImageSide: CGFloat = 2560

    /// Source app icon. The system one, from the bundle itself — like Paste does:
    /// it shows where an entry came from faster than reading the label
    private static var iconCache: [String: NSImage] = [:]

    static func sourceIcon(_ id: String?) -> NSImage? {
        guard let id else { return nil }
        if let cached = iconCache[id] { return cached }
        guard let url = NSWorkspace.shared.urlForApplication(withBundleIdentifier: id)
        else { return nil }
        let icon = NSWorkspace.shared.icon(forFile: url.path)
        iconCache[id] = icon
        return icon
    }

    private nonisolated static func store(png: Data) -> String? {
        let name = UUID().uuidString + ".png"
        do {
            try png.write(to: imagesDirectory.appending(path: name))
            return name
        } catch {
            return nil
        }
    }

    /// Content fingerprint for image dedup — SHA-256 of the stored bytes
    private nonisolated static func hash(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    /// Image to store: small ones as-is, large ones scaled down. A slightly
    /// smaller copy beats filling the disk with screenshots
    private static func compressed(_ data: Data) -> Data? {
        guard let rep = NSBitmapImageRep(data: data) else { return nil }
        let side = max(CGFloat(rep.pixelsWide), CGFloat(rep.pixelsHigh))
        if data.count <= maxImageBytes, side <= maxImageSide {
            return rep.representation(using: .png, properties: [:])
        }
        // Scaled via CoreGraphics, not NSImage's lockFocus: on a 6K screenshot
        // that silently returned a blank image and the entry was lost entirely
        let scale = min(maxImageSide / max(side, 1), 1)
        let width = Int(CGFloat(rep.pixelsWide) * scale)
        let height = Int(CGFloat(rep.pixelsHigh) * scale)
        guard let source = rep.cgImage, width > 0, height > 0,
              let context = CGContext(
                data: nil, width: width, height: height, bitsPerComponent: 8, bytesPerRow: 0,
                space: CGColorSpaceCreateDeviceRGB(),
                bitmapInfo: CGImageAlphaInfo.premultipliedFirst.rawValue)
        else {
            // Couldn't scale down — better to keep it as-is than lose the entry
            return rep.representation(using: .png, properties: [:])
        }
        context.interpolationQuality = .high
        context.draw(source, in: CGRect(x: 0, y: 0, width: width, height: height))
        guard let scaled = context.makeImage() else {
            return rep.representation(using: .png, properties: [:])
        }
        return NSBitmapImageRep(cgImage: scaled)
            .representation(using: .jpeg, properties: [.compressionFactor: 0.85])
    }

    /// File preview: images get scaled down, everything else gets a type icon.
    /// CGImageSource decodes only the thumbnail — NSImage(contentsOf:) decoded
    /// the entire file on the polling task's thread and froze the panel on
    /// large images
    private nonisolated static func thumbnail(of url: URL) -> Data? {
        guard let source = CGImageSourceCreateWithURL(url as CFURL, nil) else { return nil }
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: 256,
        ]
        guard let scaled = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary)
        else { return nil }
        return NSBitmapImageRep(cgImage: scaled).representation(using: .png, properties: [:])
    }

    /// Thumbnail generated and stored off the main actor — the entry is
    /// already in history; the preview attaches whenever it's ready
    private nonisolated static func makeThumbnail(of url: URL) async -> String? {
        thumbnail(of: url).flatMap { store(png: $0) }
    }

    /// Copying from history itself shouldn't grow history
    @ObservationIgnored private var ignoreOwnCopy = false

    private func add(_ item: Item) {
        // Copied the exact same thing again — the entry moves to the top instead of duplicating
        if let file = item.file, let index = items.firstIndex(where: { $0.file == file }) {
            // The freshly written thumbnail loses to the existing entry's one:
            // delete it, or every repeat copy of a file orphaned a PNG on disk
            if item.image != nil, item.image != items[index].image { removeFile(of: item) }
            var existing = items.remove(at: index)
            existing.date = item.date
            items.insert(existing, at: 0)
            trim()
            save()
            return
        }
        if let text = item.text, let index = items.firstIndex(where: { $0.text == text }) {
            var existing = items.remove(at: index)
            existing.date = item.date
            items.insert(existing, at: 0)
        } else {
            items.insert(item, at: 0)
        }
        trim()
        save()
    }

    private func trim() {
        let limit = AppSettings.shared.clipboardLimit
        guard items.count > limit else { return }
        var kept: [Item] = []
        var dropped: [Item] = []
        for item in items {
            // Pinned entries never get evicted — that's the point of pinning
            if item.pinned || kept.count < limit { kept.append(item) } else { dropped.append(item) }
        }
        items = kept
        for item in dropped { removeFile(of: item) }
    }

    // MARK: - actions

    /// Put an entry back on the pasteboard. Returns false if there's nothing to
    /// put back — e.g. the image file is no longer on disk
    @discardableResult
    func copy(_ item: Item) -> Bool {
        // Decide what to put on the pasteboard BEFORE clearing it: otherwise if
        // the image file were missing, the pasteboard would end up empty while
        // the tile reported "Copied" — losing whatever was on the pasteboard before
        let payload: (NSPasteboard) -> Void
        if let file = item.file {
            // The image path already checks its file; a copied file needs the
            // same — a deleted file used to land on the pasteboard as a dead
            // path while the capsule reported "Copied"
            guard FileManager.default.fileExists(atPath: file) else {
                sillLog("[clipboard] file no longer exists, nothing to copy: \(file)")
                return false
            }
            payload = { $0.writeObjects([URL(filePath: file) as NSURL]) }
        } else if let text = item.text {
            payload = { $0.setString(text, forType: .string) }
        } else if let name = item.image,
                  let image = NSImage(
                    contentsOf: Self.imagesDirectory.appending(path: name)) {
            // Put the object, not raw bytes: the system hands the app whichever
            // representation it understands. Large images used to be stored as
            // JPEG under the .png type, and some apps wouldn't paste them
            payload = { $0.writeObjects([image]) }
        } else {
            sillLog("[clipboard] nothing to restore to the pasteboard: entry \(item.id)")
            return false
        }

        ignoreOwnCopy = true
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        payload(pasteboard)
        lastChange = pasteboard.changeCount
        ignoreOwnCopy = false
        return true
    }

    /// Paste into whichever app has focus: put the entry on the pasteboard and
    /// send ⌘V. The synthetic keypress requires Accessibility access — without
    /// it the system silently swallows the event, so we ask first
    @discardableResult
    func pasteToFrontApp(_ item: Item) -> Bool {
        guard copy(item) else { return false }
        guard AXIsProcessTrusted() else {
            // Key as a string: the constant itself isn't safe for concurrent access in Swift 6
            let options = ["AXTrustedCheckOptionPrompt": true]
            _ = AXIsProcessTrustedWithOptions(options as CFDictionary)
            return false
        }
        // Give the panel time to leave and focus to return to the previous window before ⌘V
        DispatchQueue.main.asyncAfter(deadline: .now() + Motion.focusHandover) {
            let source = CGEventSource(stateID: .combinedSessionState)
            let down = CGEvent(keyboardEventSource: source, virtualKey: 9, keyDown: true)
            down?.flags = .maskCommand
            down?.post(tap: .cghidEventTap)
            let up = CGEvent(keyboardEventSource: source, virtualKey: 9, keyDown: false)
            up?.flags = .maskCommand
            up?.post(tap: .cghidEventTap)
        }
        return true
    }

    func togglePin(_ item: Item) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].pinned.toggle()
        save()
    }

    func remove(_ item: Item) {
        items.removeAll { $0.id == item.id }
        removeFile(of: item)
        save()
    }

    func clear() {
        for item in items { removeFile(of: item) }
        items.removeAll()
        save()
    }

    /// "Forget the last five minutes" — the reason people usually clear history at all
    func forgetLast(minutes: Int) {
        let edge = Date().addingTimeInterval(-Double(minutes) * 60)
        let dropped = items.filter { $0.date > edge && !$0.pinned }
        items.removeAll { $0.date > edge && !$0.pinned }
        for item in dropped { removeFile(of: item) }
        save()
    }

    /// The list in display order: pinned first, then by time. Computed once per
    /// history change, not every frame — sorting used to run on every gesture
    /// event while swiping between boards
    var ordered: [Item] {
        if let orderedCache, orderedStamp == items.count, orderedVersion == version {
            return orderedCache
        }
        let sorted = items.sorted { ($0.pinned ? 1 : 0, $0.date) > ($1.pinned ? 1 : 0, $1.date) }
        orderedCache = sorted
        orderedStamp = items.count
        orderedVersion = version
        return sorted
    }

    @ObservationIgnored private var orderedCache: [Item]?
    @ObservationIgnored private var orderedStamp = -1
    @ObservationIgnored private var orderedVersion = -1

    /// Prepared previews. Without this cache, `NSImage(contentsOf:)` ran every
    /// frame for every visible row — reading from disk during scrolling
    @ObservationIgnored private var previews: [String: NSImage] = [:]
    /// Load order, for eviction: the oldest half goes, not everything —
    /// a full reset made scrolling there and back re-read every file
    @ObservationIgnored private var previewOrder: [String] = []

    func image(for item: Item) -> NSImage? {
        guard let name = item.image else { return nil }
        if let cached = previews[name] { return cached }
        guard let image = NSImage(contentsOf: Self.imagesDirectory.appending(path: name))
        else { return nil }
        // Keep about as many as fit on screen with headroom
        if previews.count >= 60 {
            for old in previewOrder.prefix(30) { previews[old] = nil }
            previewOrder.removeFirst(min(30, previewOrder.count))
        }
        previews[name] = image
        previewOrder.append(name)
        return image
    }

    // MARK: - storage

    private nonisolated static var directory: URL {
        URL.applicationSupportDirectory.appending(path: "Sill/clipboard")
    }
    fileprivate nonisolated static var imagesDirectory: URL { directory.appending(path: "images") }
    private static var file: URL { directory.appending(path: "history.json") }

    /// History is needed outside the collector too: settings show a count, and
    /// "Clear" without a loaded list would wipe the file and orphan the images
    func ensureLoaded() { loadIfNeeded() }

    /// The limit was lowered in settings — applied now, not on the next copy:
    /// trim() used to run only from add(), and 200 entries sat there after
    /// the person had set the limit to 1
    func limitChanged() {
        loadIfNeeded()
        let before = items.count
        trim()
        if items.count != before { save() }
    }

    /// When expired entries were last purged. This used to run only at load time —
    /// in an app that can stay running for weeks without restarting, the
    /// retention period simply didn't work
    @ObservationIgnored private var expiredChecked = Date.distantPast

    private func dropExpiredIfDue() {
        guard Date().timeIntervalSince(expiredChecked) > 3600 else { return }
        expiredChecked = Date()
        dropExpired()
    }

    private func loadIfNeeded() {
        guard !loaded else { return }
        loaded = true
        try? FileManager.default.createDirectory(
            at: Self.imagesDirectory, withIntermediateDirectories: true)
        // Owner-only folder: history is personal
        try? FileManager.default.setAttributes(
            [.posixPermissions: 0o700], ofItemAtPath: Self.directory.path)
        guard let data = try? Data(contentsOf: Self.file) else { return }
        guard let stored = try? JSONDecoder().decode([Item].self, from: data) else {
            // Same treatment as a broken config: back up and log. Silently
            // starting empty meant the next copy overwrote the file — pinned
            // entries included — with no trace of what happened
            sillLog("[clipboard] history.json unreadable, backing up as history.broken.json")
            let backup = Self.directory.appending(path: "history.broken.json")
            try? data.write(to: backup, options: .atomic)
            return
        }
        items = stored
        dropExpired()
        purgeOrphanedImages()
    }

    /// Files in images/ that no history entry references — leftovers of old
    /// bugs (a dedup path used to orphan thumbnails; 49 files, 20 MB on a
    /// live machine). The referenced set is captured now, on the main actor,
    /// and only files older than a minute are deleted: a file written for an
    /// entry added while the sweep runs must not be caught in it
    private func purgeOrphanedImages() {
        let referenced = Set(items.compactMap(\.image))
        let dir = Self.imagesDirectory
        Task.detached(priority: .utility) {
            let files =
                (try? FileManager.default.contentsOfDirectory(
                    at: dir, includingPropertiesForKeys: [.contentModificationDateKey])) ?? []
            let edge = Date().addingTimeInterval(-60)
            var removed = 0
            for file in files where !referenced.contains(file.lastPathComponent) {
                let modified =
                    (try? file.resourceValues(forKeys: [.contentModificationDateKey]))?
                    .contentModificationDate ?? .distantPast
                guard modified < edge else { continue }
                try? FileManager.default.removeItem(at: file)
                removed += 1
            }
            if removed > 0 { sillLog("[clipboard] purged \(removed) orphaned previews") }
        }
    }

    /// Retention: old entries age out on their own so history doesn't pile up for years
    private func dropExpired() {
        let days = AppSettings.shared.clipboardDays
        guard days > 0 else { return }
        let edge = Date().addingTimeInterval(-Double(days) * 86400)
        let dropped = items.filter { $0.date < edge && !$0.pinned }
        guard !dropped.isEmpty else { return }
        items.removeAll { $0.date < edge && !$0.pinned }
        for item in dropped { removeFile(of: item) }
        save()
    }

    private func save() {
        version += 1
        guard let data = try? JSONEncoder().encode(items) else { return }
        try? data.write(to: Self.file, options: [.atomic, .completeFileProtection])
    }

    private func removeFile(of item: Item) {
        guard let name = item.image else { return }
        previews[name] = nil
        try? FileManager.default.removeItem(at: Self.imagesDirectory.appending(path: name))
    }

    fileprivate static func png(from data: Data) -> Data? {
        guard let rep = NSBitmapImageRep(data: data) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }
}
